package edu.bsu.cs222;

import java.util.HashMap;
import java.util.Map;

public class languageNameToCode {
    public static String mapLanguageNameToCode(String languageName) {
        Map<String, String> languageMappings = new HashMap<>();
        languageMappings.put("Afrikaans", "af");
        languageMappings.put("Albanian", "sq");
        languageMappings.put("Amharic", "am");
        languageMappings.put("Arabic", "ar");
        languageMappings.put("Armenian", "hy");
        languageMappings.put("Assamese", "as");
        languageMappings.put("Aymara", "ay");
        languageMappings.put("Azerbaijani", "az");
        languageMappings.put("Bambara", "bm");
        languageMappings.put("Basque", "eu");
        languageMappings.put("Belarusian", "be");
        languageMappings.put("Bengali", "bn");
        languageMappings.put("Bhojpuri", "bho");
        languageMappings.put("Bosnian", "bs");
        languageMappings.put("Bulgarian", "bg");
        languageMappings.put("Catalan", "ca");
        languageMappings.put("Chinese (Simplified)", "zh-CN");
        languageMappings.put("Chinese (Traditional)", "zh-TW");
        languageMappings.put("Cebuano", "ceb");
        languageMappings.put("Corsican", "co");
        languageMappings.put("Croatian", "hr");
        languageMappings.put("Czech", "cs");
        languageMappings.put("Danish", "da");
        languageMappings.put("Dhivehi", "dv");
        languageMappings.put("Dogri", "doi");
        languageMappings.put("Dutch", "nl");
        languageMappings.put("English", "en");
        languageMappings.put("Esperanto", "eo");
        languageMappings.put("Estonian", "et");
        languageMappings.put("Ewe", "ee");
        languageMappings.put("Filipino (Tagalog)", "fil");
        languageMappings.put("Finnish", "fi");
        languageMappings.put("French", "fr");
        languageMappings.put("Frisian", "fy");
        languageMappings.put("Galician", "gl");
        languageMappings.put("Georgian", "ka");
        languageMappings.put("German", "de");
        languageMappings.put("Greek", "el");
        languageMappings.put("Guarani", "gn");
        languageMappings.put("Gujarati", "gu");
        languageMappings.put("Haitian Creole", "ht");
        languageMappings.put("Hausa", "ha");
        languageMappings.put("Hawaiian", "haw");
        languageMappings.put("Hebrew", "iw");
        languageMappings.put("Hindi", "hi");
        languageMappings.put("Hmong", "hmn");
        languageMappings.put("Hungarian", "hu");
        languageMappings.put("Icelandic", "is");
        languageMappings.put("Igbo", "ig");
        languageMappings.put("Ilocano", "ilo");
        languageMappings.put("Indonesian", "id");
        languageMappings.put("Irish", "ga");
        languageMappings.put("Italian", "it");
        languageMappings.put("Japanese", "ja");
        languageMappings.put("Javanese", "jv");
        languageMappings.put("Kannada", "kn");
        languageMappings.put("Kazakh", "kk");
        languageMappings.put("Khmer", "km");
        languageMappings.put("Kinyarwanda", "rw");
        languageMappings.put("Konkani", "gom");
        languageMappings.put("Korean", "ko");
        languageMappings.put("Krio", "kri");
        languageMappings.put("Kurdish", "ku");
        languageMappings.put("Kurdish (Sorani)", "ckb");
        languageMappings.put("Kyrgyz", "ky");
        languageMappings.put("Lao", "lo");
        languageMappings.put("Latin", "la");
        languageMappings.put("Latvian", "lv");
        languageMappings.put("Lingala", "ln");
        languageMappings.put("Lithuanian", "lt");
        languageMappings.put("Luxembourgish", "lb");
        languageMappings.put("Macedonian", "mk");
        languageMappings.put("Maithili", "mai");
        languageMappings.put("Malagasy", "mg");
        languageMappings.put("Malay", "ms");
        languageMappings.put("Malayalam", "ml");
        languageMappings.put("Maltese", "mt");
        languageMappings.put("Maori", "mi");
        languageMappings.put("Marathi", "mr");
        languageMappings.put("Meiteilon (Manipuri)", "mni-Mtei");
        languageMappings.put("Mizo", "lus");
        languageMappings.put("Mongolian", "mn");
        languageMappings.put("Myanmar (Burmese)", "my");
        languageMappings.put("Nepali", "ne");
        languageMappings.put("Norwegian", "no");
        languageMappings.put("Nyanja (Chichewa)", "ny");
        languageMappings.put("Odia (Oriya)", "or");
        languageMappings.put("Oromo", "om");
        languageMappings.put("Pashto", "ps");
        languageMappings.put("Persian", "fa");
        languageMappings.put("Polish", "pl");
        languageMappings.put("Portuguese (Portugal, Brazil)", "pt");
        languageMappings.put("Punjabi", "pa");
        languageMappings.put("Quechua", "qu");
        languageMappings.put("Romanian", "ro");
        languageMappings.put("Russian", "ru");
        languageMappings.put("Samoan", "sm");
        languageMappings.put("Sanskrit", "sa");
        languageMappings.put("Scots Gaelic", "gd");
        languageMappings.put("Sepedi", "nso");
        languageMappings.put("Serbian", "sr");
        languageMappings.put("Sesotho", "st");
        languageMappings.put("Shona", "sn");
        languageMappings.put("Sindhi", "sd");
        languageMappings.put("Sinhala (Sinhalese)", "si");
        languageMappings.put("Slovak", "sk");
        languageMappings.put("Slovenian", "sl");
        languageMappings.put("Somali", "so");
        languageMappings.put("Spanish", "es");
        languageMappings.put("Sundanese", "su");
        languageMappings.put("Swahili", "sw");
        languageMappings.put("Swedish", "sv");
        languageMappings.put("Tagalog (Filipino)", "tl");
        languageMappings.put("Tajik", "tg");
        languageMappings.put("Tamil", "ta");
        languageMappings.put("Tatar", "tt");
        languageMappings.put("Telugu", "te");
        languageMappings.put("Thai", "th");
        languageMappings.put("Tigrinya", "ti");
        languageMappings.put("Tsonga", "ts");
        languageMappings.put("Turkmen", "tk");
        languageMappings.put("Twi (Akan)", "ak");
        languageMappings.put("Ukrainian", "uk");
        languageMappings.put("Urdu", "ur");
        languageMappings.put("Uyghur", "ug");
        languageMappings.put("Uzbek", "uz");
        languageMappings.put("Vietnamese", "vi");
        languageMappings.put("Welsh", "cy");
        languageMappings.put("Xhosa", "xh");
        languageMappings.put("Yiddish", "yi");
        languageMappings.put("Yoruba", "yo");
        languageMappings.put("Zulu", "zu");

        return languageMappings.get(languageName);
    }
}