package edu.bsu.cs222;

import java.util.HashMap;
import java.util.Map;

public class languageNameToCode {
    public static String mapLanguageNameToCode(String languageName) {
        Map<String, String> languageMappings = new HashMap<>();
        languageMappings.put("Afrikaans", "af");
        languageMappings.put("Albanian (shqipe)", "sq");
        languageMappings.put("Amharic", "am");
        languageMappings.put("Arabic (عربي)", "ar");
        languageMappings.put("Armenian (Հայերեն)", "hy");
        languageMappings.put("Assamese (অসমীয়া)", "as");
        languageMappings.put("Aymara", "ay");
        languageMappings.put("Azerbaijani (Azərbaycanca)", "az");
        languageMappings.put("Bambara (Bamanankan)", "bm");
        languageMappings.put("Basque (Euskara)", "eu");
        languageMappings.put("Belarusian (Беларуская)", "be");
        languageMappings.put("Bengali (বাংলা)", "bn");
        languageMappings.put("Bhojpuri (भोजपुरी)", "bho");
        languageMappings.put("Bosnian (Bosanski)", "bs");
        languageMappings.put("Bulgarian (Български)", "bg");
        languageMappings.put("Catalan (Català)", "ca");
        languageMappings.put("Chinese Simplified （中文 简体）", "zh-CN");
        languageMappings.put("Chinese Traditional （中文 繁體）", "zh-TW");
        languageMappings.put("Cebuano (Sinugboanon, Binisaya sa Sugbo)", "ceb");
        languageMappings.put("Corsican (Corsu)", "co");
        languageMappings.put("Croatian (Hrvatski)", "hr");
        languageMappings.put("Czech (Čeština)", "cs");
        languageMappings.put("Danish (Dansk)", "da");
        languageMappings.put("Dhivehi (ދިވެހި)", "dv");
        languageMappings.put("Dogri (डोगरी)", "doi");
        languageMappings.put("Dutch (Nederlands)", "nl");
        languageMappings.put("English", "en");
        languageMappings.put("Esperanto", "eo");
        languageMappings.put("Estonian (Eesti keel)", "et");
        languageMappings.put("Ewe (Eʋegbe)", "ee");
        languageMappings.put("Filipino (Tagalog)", "fil");
        languageMappings.put("Finnish (Suomi)", "fi");
        languageMappings.put("French (Français)", "fr");
        languageMappings.put("Frisian (Frysk)", "fy");
        languageMappings.put("Galician (Galego)", "gl");
        languageMappings.put("Georgian (ქართული)", "ka");
        languageMappings.put("German (Deutsch)", "de");
        languageMappings.put("Greek (Ελληνικά)", "el");
        languageMappings.put("Guarani(Avañe'ẽ)", "gn");
        languageMappings.put("Gujarati (ગુજરાતી)", "gu");
        languageMappings.put("Haitian Creole (Kreyòl Ayisyen)", "ht");
        languageMappings.put("Hausa (هَوُسَ)", "ha");
        languageMappings.put("Hawaiian (ʻŌlelo Hawaiʻi)", "haw");
        languageMappings.put("Hebrew (עברית)", "iw");
        languageMappings.put("Hindi (हिन्दी)", "hi");
        languageMappings.put("Hmong (Moob)", "hmn");
        languageMappings.put("Hungarian (Magyar)", "hu");
        languageMappings.put("Icelandic (Íslenska)", "is");
        languageMappings.put("Igbo", "ig");
        languageMappings.put("Ilocano", "ilo");
        languageMappings.put("Indonesian (Bahasa Indonesia)", "id");
        languageMappings.put("Irish (Gaeilge)", "ga");
        languageMappings.put("Italian (Italiano)", "it");
        languageMappings.put("Japanese (日本語)", "ja");
        languageMappings.put("Javanese", "jv");
        languageMappings.put("Kannada (ಕನ್ನಡ)", "kn");
        languageMappings.put("Kazakh (қазақ тілі)", "kk");
        languageMappings.put("Khmer (ភាសាខ្មែរ)", "km");
        languageMappings.put("Kinyarwanda (Ikinyarwanda)", "rw");
        languageMappings.put("Konkani (कोंकणी)", "gom");
        languageMappings.put("Korean (한국어)", "ko");
        languageMappings.put("Krio", "kri");
        languageMappings.put("Kurdish (کوردی)", "ku");
        languageMappings.put("Kurdish Sorani (کوردی سۆرانی)", "ckb");
        languageMappings.put("Kyrgyz (Кыргызча)", "ky");
        languageMappings.put("Lao (ພາສາລາວ)", "lo");
        languageMappings.put("Latin (Latina)", "la");
        languageMappings.put("Latvian (latviešu valoda)", "lv");
        languageMappings.put("Lingala (Lingála)", "ln");
        languageMappings.put("Lithuanian (lietuvių kalba)", "lt");
        languageMappings.put("Luxembourgish (Lëtzebuergesch)", "lb");
        languageMappings.put("Macedonian (Македонски)", "mk");
        languageMappings.put("Maithili (मैथिली)", "mai");
        languageMappings.put("Malagasy", "mg");
        languageMappings.put("Malay (Bahasa Melayu)", "ms");
        languageMappings.put("Malayalam (മലയാളം)", "ml");
        languageMappings.put("Maltese (Malti)", "mt");
        languageMappings.put("Maori (Māori)", "mi");
        languageMappings.put("Marathi (मराठी)", "mr");
        languageMappings.put("Meiteilon (মৈতৈলোন)", "mni-Mtei");
        languageMappings.put("Mizo (Mizo ṭawng)", "lus");
        languageMappings.put("Mongolian (Монгол)", "mn");
        languageMappings.put("Myanmar Burmese (မြန်မာစာ)", "my");
        languageMappings.put("Nepali (नेपाली)", "ne");
        languageMappings.put("Norwegian (norsk)", "no");
        languageMappings.put("Nyanja (Chichewa)", "ny");
        languageMappings.put("Odia (ଓଡ଼ିଆ)", "or");
        languageMappings.put("Oromo (Afaan Oromoo)", "om");
        languageMappings.put("Pashto (پښتو)", "ps");
        languageMappings.put("Persian (فارسی)", "fa");
        languageMappings.put("Polish (polski)", "pl");
        languageMappings.put("Portuguese (Português)", "pt");
        languageMappings.put("Punjabi (ਪੰਜਾਬੀ)", "pa");
        languageMappings.put("Quechua (Runasimi)", "qu");
        languageMappings.put("Romanian (Română)", "ro");
        languageMappings.put("Russian (Русский)", "ru");
        languageMappings.put("Samoan (Gagana Samoa)", "sm");
        languageMappings.put("Sanskrit (संस्कृतम्)", "sa");
        languageMappings.put("Scots Gaelic (Gàidhlig)", "gd");
        languageMappings.put("Sepedi", "nso");
        languageMappings.put("Serbian (Српски)", "sr");
        languageMappings.put("Sesotho", "st");
        languageMappings.put("Shona (chiShona)", "sn");
        languageMappings.put("Sindhi (سنڌي)", "sd");
        languageMappings.put("Sinhala (සිංහල)", "si");
        languageMappings.put("Slovak (Slovenčina)", "sk");
        languageMappings.put("Slovenian (Slovenščina)", "sl");
        languageMappings.put("Somali (Soomaali)", "so");
        languageMappings.put("Spanish (Español)", "es");
        languageMappings.put("Sundanese (Basa Sunda)", "su");
        languageMappings.put("Swahili (Kiswahili)", "sw");
        languageMappings.put("Swedish (Svenska)", "sv");
        languageMappings.put("Tagalog (Filipino)", "tl");
        languageMappings.put("Tajik (Тоҷикӣ)", "tg");
        languageMappings.put("Tamil (தமிழ்)", "ta");
        languageMappings.put("Tatar (Татарча)", "tt");
        languageMappings.put("Telugu (తెలుగు)", "te");
        languageMappings.put("Thai (ไทย)", "th");
        languageMappings.put("Tigrinya", "ti");
        languageMappings.put("Tsonga (Xitsonga)", "ts");
        languageMappings.put("Turkmen (Türkmençe)", "tk");
        languageMappings.put("Twi (Akan)", "ak");
        languageMappings.put("Ukrainian (Українська)", "uk");
        languageMappings.put("Urdu (اردو)", "ur");
        languageMappings.put("Uyghur (ئۇيغۇرچە)", "ug");
        languageMappings.put("Uzbek (Ўзбек тили)", "uz");
        languageMappings.put("Vietnamese (Tiếng Việt)", "vi");
        languageMappings.put("Welsh (Cymraeg)", "cy");
        languageMappings.put("Xhosa (isiXhosa)", "xh");
        languageMappings.put("Yiddish (ייִדיש)", "yi");
        languageMappings.put("Yoruba (Èdè Yorùbá)", "yo");
        languageMappings.put("Zulu (isiZulu)", "zu");

        return languageMappings.get(languageName);
    }
}